"""
This type stub file was generated by pyright.
"""

__all__ = ['quad', 'dblquad', 'tplquad', 'nquad', 'quad_explain', 'IntegrationWarning', 'error']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

