"""
This type stub file was generated by pyright.
"""

__all__ = ['solve', 'solve_triangular', 'solveh_banded', 'solve_banded', 'solve_toeplitz', 'solve_circulant', 'inv', 'det', 'lstsq', 'pinv', 'pinv2', 'pinvh', 'matrix_balance', 'matmul_toeplitz', 'atleast_1d', 'atleast_2d', 'get_flinalg_funcs', 'get_lapack_funcs', 'LinAlgError', 'LinAlgWarning', 'decomp', 'decomp_svd', 'levinson']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

