"""
This type stub file was generated by pyright.
"""

__all__ = ['expm', 'inv', 'float_factorial', 'solve', 'solve_triangular', 'isspmatrix', 'spsolve', 'is_pydata_spmatrix', 'LinearOperator', 'UPPER_TRIANGULAR', 'MatrixPowerOperator', 'ProductOperator']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

