"""
This type stub file was generated by pyright.
"""

def isNPY_OLD(): # -> bool:
    '''
    A new random C API was added in 1.18 and became stable in 1.19.
    Prefer the new random C API when building with recent numpy.
    '''
    ...

def make_biasedurn(): # -> None:
    '''Substitute True/False values for NPY_OLD Cython build variable.'''
    ...

def make_unuran(): # -> None:
    """Substitute True/False values for NPY_OLD Cython build variable."""
    ...

def make_boost(): # -> None:
    ...

if __name__ == '__main__':
    ...
