"""
This type stub file was generated by pyright.
"""

import numpy as np
from scipy._lib._util import IntNumber
from typing_extensions import Literal

def initialize_v(v: np.ndarray, dim: IntNumber) -> None:
    ...

def initialize_direction_numbers() -> None:
    ...

_MAXDIM: Literal[21201]
_MAXBIT: Literal[30]
_MAXDEG: Literal[18]
