"""
This type stub file was generated by pyright.
"""

import logging
from fontTools.misc.loggingTools import deprecateFunction
from fontTools.ttLib.ttFont import *

# from fontTools.ttLib.ttCollection import TTCollection

"""fontTools.ttLib -- a package for dealing with TrueType fonts."""
log: logging.Logger = ...

class TTLibError(Exception): ...

@deprecateFunction("use logging instead", category=DeprecationWarning)
def debugmsg(msg: str) -> None: ...
