"""
This type stub file was generated by pyright.
"""

class _UnicodeCustom:
	def __init__(self, f) -> None:
		...
	
	def __getitem__(self, charCode): # -> Literal['????']:
		...
	


class _UnicodeBuiltin:
	def __getitem__(self, charCode):
		...
	


Unicode = ...
def setUnicodeData(f): # -> None:
	...

