"""
This type stub file was generated by pyright.
"""

"""\
Provides functions that help in using BCP 47 language tags.
"""
_shortLanguageTags = ...
_expandedLanguageTags = ...
_nameTableThreeLetterLanguageCodes = ...
def shortenLanguageTag(tag):
    """\
    Returns the shortened version of tag if tag consists of a language
    subtag and the likely region subtag for that language;
    the original tag otherwise.
    """
    ...

def expandLanguageTag(tag):
    """\
    Returns the expanded version of tag adding the likely
    region subtag if tag consists of just a language
    subtag and we have a likely country for it;
    the original tag otherwise.
    """
    ...

