"""
This type stub file was generated by pyright.
"""

"""\
Provides low-level types for use throughout the FontDocTools package.
"""
class Percentage(float):
    """\
    This class marks the encapsulated number as a percentage value.
    """
    ...


