"""
This type stub file was generated by pyright.
"""

from . import DefaultTable

CVAR_HEADER_FORMAT = ...
CVAR_HEADER_SIZE = ...
class table__c_v_a_r(DefaultTable.DefaultTable):
    dependencies = ...
    def __init__(self, tag=...) -> None:
        ...
    
    def compile(self, ttFont, useSharedPoints=...): # -> bytes:
        ...
    
    def decompile(self, data, ttFont): # -> None:
        ...
    
    def fromXML(self, name, attrs, content, ttFont): # -> None:
        ...
    
    def toXML(self, writer, ttFont): # -> None:
        ...
    


