"""
This type stub file was generated by pyright.
"""

from . import DefaultTable

class table__c_v_t(DefaultTable.DefaultTable):
	def decompile(self, data, ttFont): # -> None:
		...
	
	def compile(self, ttFont): # -> bytes:
		...
	
	def toXML(self, writer, ttFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, ttFont): # -> None:
		...
	
	def __len__(self): # -> int:
		...
	
	def __getitem__(self, index): # -> int:
		...
	
	def __setitem__(self, index, value): # -> None:
		...
	
	def __delitem__(self, index): # -> None:
		...
	


