"""
This type stub file was generated by pyright.
"""

import fontTools.ttLib.tables.TupleVariation as tv
from . import DefaultTable

log = ...
TupleVariation = tv.TupleVariation
GVAR_HEADER_FORMAT = ...
GVAR_HEADER_SIZE = ...
class table__g_v_a_r(DefaultTable.DefaultTable):
	dependencies = ...
	def __init__(self, tag=...) -> None:
		...
	
	def compile(self, ttFont): # -> bytes:
		...
	
	def compileGlyphs_(self, ttFont, axisTags, sharedCoordIndices): # -> list[Unknown]:
		...
	
	def decompile(self, data, ttFont): # -> None:
		...
	
	@staticmethod
	def decompileOffsets_(data, tableFormat, glyphCount): # -> list[int] | array[int]:
		...
	
	@staticmethod
	def compileOffsets_(offsets): # -> tuple[bytes, Literal[0, 1]]:
		"""Packs a list of offsets into a 'gvar' offset table.

		Returns a pair (bytestring, tableFormat). Bytestring is the
		packed offset table. Format indicates whether the table
		uses short (tableFormat=0) or long (tableFormat=1) integers.
		The returned tableFormat should get packed into the flags field
		of the 'gvar' header.
		"""
		...
	
	def toXML(self, writer, ttFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, ttFont):
		...
	
	@staticmethod
	def getNumPoints_(glyph): # -> int:
		...
	


def compileGlyph_(variations, pointCount, axisTags, sharedCoordIndices): # -> bytes:
	...

def decompileGlyph_(pointCount, sharedTuples, axisTags, data): # -> list[Unknown]:
	...

