"""
This type stub file was generated by pyright.
"""

from . import DefaultTable

log = ...
headFormat = ...
class table__h_e_a_d(DefaultTable.DefaultTable):
	dependencies = ...
	def decompile(self, data, ttFont): # -> None:
		...
	
	def compile(self, ttFont):
		...
	
	def toXML(self, writer, ttFont):
		...
	
	def fromXML(self, name, attrs, content, ttFont): # -> None:
		...
	


