"""
This type stub file was generated by pyright.
"""

from . import DefaultTable

hheaFormat = ...
class table__h_h_e_a(DefaultTable.DefaultTable):
	dependencies = ...
	@property
	def ascender(self):
		...
	
	@ascender.setter
	def ascender(self, value): # -> None:
		...
	
	@property
	def descender(self):
		...
	
	@descender.setter
	def descender(self, value): # -> None:
		...
	
	def decompile(self, data, ttFont): # -> None:
		...
	
	def compile(self, ttFont): # -> bytes:
		...
	
	def recalc(self, ttFont):
		...
	
	def toXML(self, writer, ttFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, ttFont): # -> None:
		...
	


