"""
This type stub file was generated by pyright.
"""

from . import DefaultTable

log = ...
class table__k_e_r_n(DefaultTable.DefaultTable):
	def getkern(self, format): # -> None:
		...
	
	def decompile(self, data, ttFont):
		...
	
	def compile(self, ttFont): # -> bytes:
		...
	
	def toXML(self, writer, ttFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, ttFont): # -> None:
		...
	


class KernTable_format_0:
	version = ...
	def __init__(self, apple=...) -> None:
		...
	
	def decompile(self, data, ttFont):
		...
	
	def compile(self, ttFont):
		...
	
	def toXML(self, writer, ttFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, ttFont): # -> None:
		...
	
	def __getitem__(self, pair):
		...
	
	def __setitem__(self, pair, value): # -> None:
		...
	
	def __delitem__(self, pair): # -> None:
		...
	


class KernTable_format_unkown:
	def __init__(self, format) -> None:
		...
	
	def decompile(self, data, ttFont): # -> None:
		...
	
	def compile(self, ttFont):
		...
	
	def toXML(self, writer, ttFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, ttFont): # -> None:
		...
	


kern_classes = ...
