"""
This type stub file was generated by pyright.
"""

from . import DefaultTable

class table__l_t_a_g(DefaultTable.DefaultTable):
	def __init__(self, tag=...) -> None:
		...
	
	def addTag(self, tag): # -> int:
		"""Add 'tag' to the list of langauge tags if not already there.

		Returns the integer index of 'tag' in the list of all tags.
		"""
		...
	
	def decompile(self, data, ttFont): # -> None:
		...
	
	def compile(self, ttFont): # -> bytes:
		...
	
	def toXML(self, writer, ttFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, ttFont): # -> None:
		...
	


