"""
This type stub file was generated by pyright.
"""

from . import DefaultTable

maxpFormat_0_5 = ...
maxpFormat_1_0_add = ...
class table__m_a_x_p(DefaultTable.DefaultTable):
	dependencies = ...
	def decompile(self, data, ttFont): # -> None:
		...
	
	def compile(self, ttFont): # -> bytes:
		...
	
	def recalc(self, ttFont):
		"""Recalculate the font bounding box, and most other maxp values except
		for the TT instructions values. Also recalculate the value of bit 1
		of the flags field and the font bounding box of the 'head' table.
		"""
		...
	
	def testrepr(self): # -> None:
		...
	
	def toXML(self, writer, ttFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, ttFont): # -> None:
		...
	


