"""
This type stub file was generated by pyright.
"""

from . import DefaultTable

vheaFormat = ...
class table__v_h_e_a(DefaultTable.DefaultTable):
	dependencies = ...
	def decompile(self, data, ttFont): # -> None:
		...
	
	def compile(self, ttFont): # -> bytes:
		...
	
	def recalc(self, ttFont):
		...
	
	def toXML(self, writer, ttFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, ttFont): # -> None:
		...
	
	@property
	def reserved0(self):
		...
	
	@reserved0.setter
	def reserved0(self, value): # -> None:
		...
	


