"""
This type stub file was generated by pyright.
"""

from . import E_B_D_T_
from .E_B_D_T_ import BitmapGlyph, BitmapPlusBigMetricsMixin, BitmapPlusSmallMetricsMixin

class table_C_B_D_T_(E_B_D_T_.table_E_B_D_T_):
	locatorName = ...
	def getImageFormatClass(self, imageFormat): # -> Type[ebdt_bitmap_format_1] | Type[ebdt_bitmap_format_2] | Type[ebdt_bitmap_format_5] | Type[ebdt_bitmap_format_6] | Type[ebdt_bitmap_format_7] | Type[ebdt_bitmap_format_8] | Type[ebdt_bitmap_format_9] | Type[cbdt_bitmap_format_17] | Type[cbdt_bitmap_format_18] | Type[cbdt_bitmap_format_19]:
		...
	


class ColorBitmapGlyph(BitmapGlyph):
	fileExtension = ...
	xmlDataFunctions = ...


class cbdt_bitmap_format_17(BitmapPlusSmallMetricsMixin, ColorBitmapGlyph):
	def decompile(self): # -> None:
		...
	
	def compile(self, ttFont): # -> bytes:
		...
	


class cbdt_bitmap_format_18(BitmapPlusBigMetricsMixin, ColorBitmapGlyph):
	def decompile(self): # -> None:
		...
	
	def compile(self, ttFont): # -> bytes:
		...
	


class cbdt_bitmap_format_19(ColorBitmapGlyph):
	def decompile(self): # -> None:
		...
	
	def compile(self, ttFont):
		...
	


cbdt_bitmap_classes = ...
