"""
This type stub file was generated by pyright.
"""

from . import DefaultTable

class table_C_F_F_(DefaultTable.DefaultTable):
	def __init__(self, tag=...) -> None:
		...
	
	def decompile(self, data, otFont): # -> None:
		...
	
	def compile(self, otFont): # -> bytes:
		...
	
	def haveGlyphNames(self): # -> bool:
		...
	
	def getGlyphOrder(self):
		...
	
	def setGlyphOrder(self, glyphOrder): # -> None:
		...
	
	def toXML(self, writer, otFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, otFont): # -> None:
		...
	


