"""
This type stub file was generated by pyright.
"""

from . import DefaultTable

GMAPFormat = ...
GMAPRecordFormat1 = ...
class GMAPRecord:
	def __init__(self, uv=..., cid=..., gid=..., ggid=..., name=...) -> None:
		...
	
	def toXML(self, writer, ttFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, ttFont): # -> None:
		...
	
	def compile(self, ttFont): # -> bytes:
		...
	
	def __repr__(self): # -> str:
		...
	


class table_G_M_A_P_(DefaultTable.DefaultTable):
	dependencies = ...
	def decompile(self, data, ttFont): # -> None:
		...
	
	def compile(self, ttFont): # -> bytes:
		...
	
	def toXML(self, writer, ttFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, ttFont): # -> None:
		...
	


