"""
This type stub file was generated by pyright.
"""

def decompress(data): # -> tuple[Unknown, Any]:
    ...

def compress(scheme, data):
    ...

def entries(attributes, sameval=...): # -> Generator[tuple[Unknown | int, int, list[Unknown]], None, None]:
    ...

def bininfo(num, size=...): # -> bytes:
    ...

def num2tag(n): # -> str | Any:
    ...

def tag2num(n): # -> int | Any:
    ...

