"""
This type stub file was generated by pyright.
"""

from . import DefaultTable

SINGFormat = ...
class table_S_I_N_G_(DefaultTable.DefaultTable):
	dependencies = ...
	def decompile(self, data, ttFont): # -> None:
		...
	
	def decompileUniqueName(self, data):
		...
	
	def compile(self, ttFont): # -> bytes:
		...
	
	def compilecompileUniqueName(self, name, length):
		...
	
	def toXML(self, writer, ttFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, ttFont): # -> None:
		...
	


