"""
This type stub file was generated by pyright.
"""

sbixGlyphHeaderFormat = ...
sbixGlyphHeaderFormatSize = ...
class Glyph:
	def __init__(self, glyphName=..., referenceGlyphName=..., originOffsetX=..., originOffsetY=..., graphicType=..., imageData=..., rawdata=..., gid=...) -> None:
		...
	
	def decompile(self, ttFont): # -> None:
		...
	
	def compile(self, ttFont): # -> None:
		...
	
	def toXML(self, xmlWriter, ttFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, ttFont): # -> None:
		...
	


