"""
This type stub file was generated by pyright.
"""

from . import asciiTable

class table_T_S_I_V_(asciiTable.asciiTable):
	def toXML(self, writer, ttFont): # -> None:
		...
	
	def fromXML(self, name, attrs, content, ttFont): # -> None:
		...
	


