"""
This type stub file was generated by pyright.
"""

"""
Compatibility tools for various data structure inputs
"""
def is_data_frame(obj): # -> bool:
    ...

def is_design_matrix(obj): # -> bool:
    ...

def interpret_data(data, colnames=..., rownames=...): # -> tuple[NDArray[_SCT@asarray] | Unknown, list[Unknown] | list[str] | Unknown, Unknown | None]:
    """
    Convert passed data structure to form required by estimation classes

    Parameters
    ----------
    data : array_like
    colnames : sequence or None
        May be part of data structure
    rownames : sequence or None

    Returns
    -------
    (values, colnames, rownames) : (homogeneous ndarray, list)
    """
    ...

def struct_to_ndarray(arr):
    ...

