"""
This type stub file was generated by pyright.
"""

def iup_segment(coords, rc1, rd1, rc2, rd2):
	...

def iup_contour(delta, coords):
	...

def iup_delta(delta, coords, ends): # -> list[Unknown]:
	...

def can_iup_in_between(deltas, coords, i, j, tolerance): # -> bool:
	...

def iup_contour_optimize(delta, coords, tolerance=...):
	...

def iup_delta_optimize(delta, coords, ends, tolerance=...): # -> list[Unknown]:
	...

